### ISSUE TITLE
movie-list-section > movie-card

### ISSUE THREAD

**Issue by DuetoPark** [DuetoPark/movie-2#3]
### 원하는 동작
1. movie-card에 마우스를 올린다
2. movie-card-info의 크기가 커진다
3. movie-card-info가 movie-card를 터트리고 튀어나간다

### 실제 동작
- movie-card-info가 movie-card를 터트리지 못한다

### 마크업
```html
<div class="movie-card">
  <div class="movie-card-info"></div>
</div>
```

### 스타일
```scss
.movie-card {
  overflow: hidden;

  &:hover {
    .movie-card-info {
      transform: scale(1.1);
    }
  }

  .movie-card-info {
    @include pos-center;
  }
}
```
